name: Run Playwright Tests

#on: Déclenche la pipeline à chaque push ou pull request sur main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
#checkout Clone le repo dans l'environment de CI
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
#setup-node Configure Node.js pour exécuter les tests.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload test report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
